name: anvio-dev
channels:
- conda-forge
- bioconda
- defaults
dependencies:
- python=3.7
- sqlite
- prodigal
- idba
- mcl
- muscle=3.8.1551
- hmmer
- diamond
- blast
- bowtie2
- bwa
- graphviz
- "samtools>=1.9"
- trimal
- iqtree
- trnascan-se