name: anvio-dev
channels:
- conda-forge
- bioconda
- defaults
dependencies:
- python=3.7
- sqlite
- prodigal
- idba
- mcl
- muscle=3.8.1551
- famsa
- sra-tools
- hmmer
- diamond
- blast
- megahit
- spades
- bowtie2
- bwa
- graphviz
- "samtools>=1.9"
- trimal
- iqtree
- trnascan-se
- fasttree
- vmatch
- r-base
- r-tidyverse
- r-optparse
- r-stringi
- r-magrittr
- bioconductor-qvalue
- fastani