name: Daily Component Tests and Migrations

on:
  schedule:
    - cron: "0 9 * * *"

jobs:
  build:
    name: Daily Component Tests (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: 'latest'
        auto-update-conda: true
        activate-environment: anvio_env
        environment-file: .conda/environment.yaml
        python-version: ${{ matrix.python-version }}
    - name: "Conda environment summary"
      shell: bash -l {0}
      run: |
        conda info
        conda list
    - uses: actions/checkout@v2
    - name: "Install anvi'o from the codebase"
      shell: bash -l {0}
      run: |
        pip install .
    - name: "Run component tests"
      shell: bash -l {0}
      run: |
        anvi-self-test --suite metagenomics-full --no-interactive
        anvi-self-test --suite pangenomics --no-interactive
        anvi-self-test --suite inversions --no-interactive
# the following steps cause our actions to fail on GitHub runners
# due to space limitations :/ please do not uncomment this until we
# have a solution for this :/
    #- name: "Run component tests for metabolism framework"
    #  shell: bash -l {0}
    #  run: |
    #    anvi-self-test --suite metabolism --no-interactive
    #- name: "Migrate ancient anvi'o databases"
    #  shell: bash -l {0}
    #  run: |
    #    anvi-self-test --suite database-migrations
