name: Daily Component Tests and Migrations

on:
  schedule:
    - cron: "0 9 * * *"

jobs:
  build:
    name: Daily Component Tests (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
      fail-fast: false
    steps:
    - name: "Clear GitHub Actions Cache"
      run: |
        rm -rf node_modules
        rm -rf .git/modules/
        rm -rf anvio/data/interactive/lib/JavaScript-MD5
        rm -rf ${{ runner.workspace }}/*

    - uses: actions/checkout@v4

    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: 'latest'
        auto-update-conda: true
        activate-environment: anvio_env
        environment-file: .conda/environment.yaml
        python-version: ${{ matrix.python-version }}

    - name: "Install Bioconductor qvalue package for R"
      shell: bash -l {0}
      run: |
        Rscript -e 'install.packages("BiocManager", repos="https://cran.rstudio.com"); BiocManager::install("qvalue")'

    - name: "Conda environment summary"
      shell: bash -l {0}
      run: |
        conda info
        conda list

    - name: "Install anvi'o from the codebase"
      shell: bash -l {0}
      run: |
        pip install .

    - name: "Set Anvi'o interactive directory path"
      shell: bash -l {0}
      run: |
        interactive_dir=$(python -c "import site; print(site.getsitepackages()[0] + '/anvio/data/interactive')")
        echo "interactive_dir_path=$interactive_dir" >> $GITHUB_ENV

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: "Install npm dependencies for Anvi'o interactive interfaces"
      shell: bash -l {0}
      run: |
        cd ${{ env.interactive_dir_path }}
        npm install
        cd -

    - name: "Run component tests"
      shell: bash -l {0}
      run: |
        anvi-self-test --suite metagenomics-full --no-interactive
        anvi-self-test --suite pangenomics --no-interactive
        anvi-self-test --suite inversions --no-interactive
# the following steps cause our actions to fail on GitHub runners
# due to space limitations :/ please do not uncomment this until we
# have a solution for this :/
    #- name: "Run component tests for metabolism framework"
    #  shell: bash -l {0}
    #  run: |
    #    anvi-self-test --suite metabolism --no-interactive
    #- name: "Migrate ancient anvi'o databases"
    #  shell: bash -l {0}
    #  run: |
    #    anvi-self-test --suite database-migrations
